name: Continuous Integration

on:
  push:
    branches: '**'

concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: coursier/cache-action@v6.4.6
    - uses: VirtusLab/scala-cli-setup@v1.3.1
    - run: scala-cli --power test .
